[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run dev:webpack"
  targetPort = 5173
  port = 8080
  publish = "dist"
  autoPublish = false