[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  framework = "vue"
  command = "npm run dev"
  targetPort = 8080
  port = 8888
  publish = "dist"
  autoPublish = false